### ISSUE TITLE
[UI][Product Card] Design Product card to look like the correct UI

### ISSUE THREAD

**Issue by Kolosafo** [Kolosafo/price-update#3]
- As per the UI I created, re-design the product card to look like it

- Including the category card that has a green Background

![WhatsApp Image 2024-02-22 at 21 03 43](https://github.com/Kolosafo/price-update/assets/88611380/f60937ed-4ad0-45d0-ac2d-e8cdb9523c2b)

**Comment by Dom-iha** [comment]
Updated product card to better fit the design
